USE QLKS;
GO

IF OBJECT_ID('dbo.TAIKHOAN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TAIKHOAN (
        MATK INT IDENTITY(1,1) PRIMARY KEY,
        MANV VARCHAR(10) NULL,
        TENDANGNHAP VARCHAR(50) NOT NULL UNIQUE,
        MATKHAU_HASH NVARCHAR(255) NOT NULL,
        VAITRO VARCHAR(20) NOT NULL DEFAULT 'LE_TAN',
        TRANGTHAI BIT NOT NULL DEFAULT 1,
        NGAYTAO DATETIME NOT NULL DEFAULT GETDATE(),
        LAN_DANG_NHAP_CUOI DATETIME NULL,

        CONSTRAINT FK_TAIKHOAN_NHANVIEN
            FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),

        CONSTRAINT CK_TAIKHOAN_VAITRO
            CHECK (VAITRO IN ('ADMIN', 'QUAN_LY', 'LE_TAN', 'KE_TOAN'))
    );
END
GO

-- User SQL Server riêng cho web, không dùng sa.
IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'hotel_web')
BEGIN
    CREATE LOGIN hotel_web WITH PASSWORD = 'Change_This_Strong_Password_123!';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'hotel_web')
BEGIN
    CREATE USER hotel_web FOR LOGIN hotel_web;
END
GO

GRANT SELECT ON SCHEMA::dbo TO hotel_web;
GRANT EXECUTE ON SCHEMA::dbo TO hotel_web;
GRANT UPDATE ON dbo.TAIKHOAN (LAN_DANG_NHAP_CUOI) TO hotel_web;
GO
